-- =============================================================
-- LLM 사용량 기록 (F-OBS) — 사용자별 토큰 사용량을 남긴다.
--
-- 왜 DB 인가: 제공자(Google)는 "내 앱"까지만 알고 "내 앱의 사용자"는 모른다.
--   응답에 실려오는 토큰 수를 받아 우리 user_seq 와 함께 남기는 것 말고는 방법이 없다.
-- 왜 Prometheus 가 아닌가: user_seq 를 라벨로 넣으면 시계열이 사용자 수만큼 늘어난다
--   (카디널리티 폭발). 운영 지표는 저차원 라벨로 Prometheus, 사용자별 사용량은 여기.
--
-- append-only. 과금·쿼터·남용 조사의 근거라 UPDATE/DELETE 하지 않는다 (admin_audit_log 와 같은 성격).
--
-- 기존 볼륨에 수동 적용:
--   docker exec -i workmate-db psql -U workmate -d workmate_db < db/init/16-llm-usage.sql
-- =============================================================

CREATE TABLE IF NOT EXISTS llm_usage (
    usage_seq     bigint GENERATED BY DEFAULT AS IDENTITY,
    user_seq      bigint      NOT NULL,
    feature       varchar(20) NOT NULL,               -- 'CHAT'|'OCR'|'STT'|'SUMMARY'|'EMBEDDING'
    model_name    varchar(50),
    -- 제공자가 usage 를 주지 않는 경로(VectorStore.add 로 감춰지는 임베딩)에서는 NULL 이다.
    -- 그 경우에도 "누가 언제 무엇을 썼는지"는 남으므로 호출 건수 집계는 가능하다.
    input_tokens  integer,
    output_tokens integer,
    created_at    timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT llm_usage_usage_seq_pk PRIMARY KEY (usage_seq)
);

-- 사용자별 기간 집계가 주 조회 패턴이다 (관리자 대시보드·월별 사용량)
CREATE INDEX IF NOT EXISTS idx_llm_usage_user_created ON llm_usage (user_seq, created_at);
-- 기능별 추세(채팅 vs 영수증 vs 음성)를 볼 때 쓴다
CREATE INDEX IF NOT EXISTS idx_llm_usage_feature_created ON llm_usage (feature, created_at);

-- 테이블·컬럼 코멘트 (프로젝트 규칙: 모든 테이블·컬럼에 COMMENT 를 단다)
COMMENT ON TABLE  llm_usage               IS 'LLM 사용량 기록 (F-OBS) — 사용자별 토큰 사용량. append-only, 과금·쿼터·남용 조사 근거';
COMMENT ON COLUMN llm_usage.usage_seq     IS '사용량 기록 식별자 (PK)';
COMMENT ON COLUMN llm_usage.user_seq      IS '사용한 사용자 식별자 (admin_user.user_seq)';
COMMENT ON COLUMN llm_usage.feature       IS '호출 기능 — CHAT(채팅)·OCR(영수증)·STT(음성전사)·SUMMARY(회의록요약)·EMBEDDING(가이드임베딩)';
COMMENT ON COLUMN llm_usage.model_name    IS '실제 호출된 모델명 — 별칭(gemini-flash-latest)이 아니라 응답이 알려준 실모델';
COMMENT ON COLUMN llm_usage.input_tokens  IS '입력(프롬프트) 토큰 수 — 제공자가 usage 를 주지 않는 경로(임베딩)에서는 NULL';
COMMENT ON COLUMN llm_usage.output_tokens IS '출력(생성) 토큰 수 — 제공자가 usage 를 주지 않는 경로(임베딩)에서는 NULL';
COMMENT ON COLUMN llm_usage.created_at    IS '기록 일시';
