-- =============================================================
-- F1-1 소셜 로그인 — 스키마 변경
-- 설계: docs/features/social-login/F1-1_SOCIAL_LOGIN_SPEC.md
--
-- 기존 볼륨 환경에 수동 적용:
--   docker exec -i workmate-db psql -U workmate -d workmate_db < db/init/14-social-login.sql
-- =============================================================

-- 소셜로 가입한 사용자는 비밀번호가 없다.
-- 이메일 로그인 사용자는 그대로 BCrypt 해시를 갖는다.
ALTER TABLE app_user ALTER COLUMN password DROP NOT NULL;

-- 계정 하나에 소셜 제공자를 여러 개 매단다.
-- app_user 에 컬럼 2개로 넣으면 "구글로 가입한 뒤 네이버도 연결"이 불가능해 별도 테이블로 뺐다.
CREATE TABLE IF NOT EXISTS user_social_account (
    social_seq        bigint GENERATED BY DEFAULT AS IDENTITY,
    user_seq          bigint       NOT NULL,             -- 연결된 계정
    provider          varchar(20)  NOT NULL,             -- 'naver' | 'google'
    provider_user_id  varchar(255) NOT NULL,             -- 제공자가 발급한 고유 식별자
    created_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_social_account_social_seq_pk PRIMARY KEY (social_seq),
    CONSTRAINT user_social_account_user_seq_fk FOREIGN KEY (user_seq) REFERENCES app_user(user_seq),
    CONSTRAINT user_social_account_provider_uk UNIQUE (provider, provider_user_id)
);

-- 로그인할 때마다 "이 계정에 붙은 소셜 목록"을 조회하므로 user_seq 인덱스를 둔다.
CREATE INDEX IF NOT EXISTS idx_user_social_account_user ON user_social_account (user_seq);
