-- =============================================================
-- V1 — 베이스라인 스키마 (Flyway 도입 시점 스냅샷)
--
-- db/init/legacy/*.sql(01~18번, .sql 만) 을 빈 컨테이너에 CI 와 동일한 순서로 적용한 뒤
-- `pg_dump --schema-only --no-owner --no-privileges` 로 뜬 결과다. 손으로 옮겨 적지 않았다.
-- 원본 dump 의 `\restrict`/`\unrestrict` 줄(pg_dump 17.10+ 신규, psql 전용 메타커맨드)은
-- Flyway(JDBC 로 SQL 을 직접 실행)가 이해하지 못해 제거했다. 그 외 내용은 dump 그대로다.
--
-- ⚠️ 적용된 뒤에는 이 파일을 손으로 고치지 말 것 — 체크섬 불일치로 기동이 깨진다.
--    스키마를 바꿔야 하면 새 버전 파일(V3__... 등)을 추가한다.
-- =============================================================
--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10 (Debian 17.10-1.pgdg12+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_audit_log (
    audit_seq bigint NOT NULL,
    admin_user_seq bigint NOT NULL,
    target_user_seq bigint NOT NULL,
    action character varying(30) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: TABLE admin_audit_log; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.admin_audit_log IS '관리자 행위 감사 로그 (F6) — append-only, UPDATE/DELETE 금지';


--
-- Name: COLUMN admin_audit_log.audit_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin_audit_log.audit_seq IS '감사 로그 식별자 (PK)';


--
-- Name: COLUMN admin_audit_log.admin_user_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin_audit_log.admin_user_seq IS '행위를 수행한 관리자 식별자';


--
-- Name: COLUMN admin_audit_log.target_user_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin_audit_log.target_user_seq IS '대상 사용자 식별자';


--
-- Name: COLUMN admin_audit_log.action; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin_audit_log.action IS '수행 행위 — UNLOCK(잠금해제) | RESET_PASSWORD(비밀번호 초기화)';


--
-- Name: COLUMN admin_audit_log.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin_audit_log.created_at IS '수행 일시';


--
-- Name: admin_audit_log_audit_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_audit_log ALTER COLUMN audit_seq ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_audit_log_audit_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    user_seq bigint NOT NULL,
    email character varying(512) NOT NULL,
    password character varying(60),
    user_name character varying(50) NOT NULL,
    phone character varying(512),
    role character varying(20) DEFAULT 'ROLE_USER'::character varying NOT NULL,
    login_fail_count integer DEFAULT 0 NOT NULL,
    locked_at timestamp without time zone,
    use_yn boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: TABLE app_user; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.app_user IS '사용자 계정 — 일반/관리자를 role 로 구분한다. 이메일·전화번호는 AES-256 암호화 저장';


--
-- Name: COLUMN app_user.user_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.app_user.user_seq IS '사용자 식별자 (PK)';


--
-- Name: COLUMN app_user.email; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.app_user.email IS '로그인 이메일 — AES-256 결정적 암호화(고정 IV). 같은 평문이 같은 암호문이라 UK·검색이 가능해 512자';


--
-- Name: COLUMN app_user.password; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.app_user.password IS '비밀번호 — BCrypt 단방향 해시(60자). 소셜 전용 계정은 임의값';


--
-- Name: COLUMN app_user.user_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.app_user.user_name IS '표시 이름';


--
-- Name: COLUMN app_user.phone; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.app_user.phone IS '전화번호 — AES-256 결정적 암호화(고정 IV)';


--
-- Name: COLUMN app_user.role; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.app_user.role IS '권한 — ROLE_USER | ROLE_ADMIN';


--
-- Name: COLUMN app_user.login_fail_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.app_user.login_fail_count IS '연속 로그인 실패 횟수 (F1-06) — 임계치 도달 시 locked_at 설정';


--
-- Name: COLUMN app_user.locked_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.app_user.locked_at IS '계정 잠금 시각 (F1-06) — 설정 후 lock-minutes 동안 로그인 차단. NULL 이면 잠금 아님';


--
-- Name: COLUMN app_user.use_yn; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.app_user.use_yn IS '사용 여부 — false 는 논리 삭제(행을 지우지 않는다)';


--
-- Name: COLUMN app_user.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.app_user.created_at IS '가입 일시';


--
-- Name: app_user_user_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN user_seq ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_user_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_message (
    message_seq bigint NOT NULL,
    room_seq bigint NOT NULL,
    role character varying(10) NOT NULL,
    content text NOT NULL,
    model_name character varying(50),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    sources jsonb
);


--
-- Name: TABLE chat_message; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.chat_message IS '채팅 메시지 (F2) — 사용자 질문과 AI 응답을 시간순으로 보관';


--
-- Name: COLUMN chat_message.message_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_message.message_seq IS '메시지 식별자 (PK)';


--
-- Name: COLUMN chat_message.room_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_message.room_seq IS '소속 채팅방 식별자 (chat_room.room_seq)';


--
-- Name: COLUMN chat_message.role; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_message.role IS '발화 주체 — user | assistant';


--
-- Name: COLUMN chat_message.content; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_message.content IS '메시지 본문 (마크다운)';


--
-- Name: COLUMN chat_message.model_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_message.model_name IS '응답 생성에 쓰인 모델명 (assistant 메시지에만)';


--
-- Name: COLUMN chat_message.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_message.created_at IS '생성 일시';


--
-- Name: COLUMN chat_message.sources; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_message.sources IS 'RAG 출처 목록 JSON (F4-07) — [{guideSeq, title}]. 대화 이력 재조회 시 출처를 복원한다';


--
-- Name: chat_message_message_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_message ALTER COLUMN message_seq ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_message_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_room; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_room (
    room_seq bigint NOT NULL,
    user_seq bigint NOT NULL,
    title character varying(100) NOT NULL,
    use_yn boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: TABLE chat_room; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.chat_room IS '채팅방 (F2) — 사용자별 대화 묶음';


--
-- Name: COLUMN chat_room.room_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_room.room_seq IS '채팅방 식별자 (PK)';


--
-- Name: COLUMN chat_room.user_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_room.user_seq IS '방 소유자 식별자 (app_user.user_seq)';


--
-- Name: COLUMN chat_room.title; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_room.title IS '방 제목 — 첫 질문에서 자동 생성 (F2-02)';


--
-- Name: COLUMN chat_room.use_yn; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_room.use_yn IS '사용 여부 — false 는 논리 삭제 (C4)';


--
-- Name: COLUMN chat_room.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chat_room.created_at IS '생성 일시';


--
-- Name: chat_room_room_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_room ALTER COLUMN room_seq ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_room_room_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: common_code; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.common_code (
    group_code character varying(30) NOT NULL,
    code character varying(50) NOT NULL,
    code_name character varying(100) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    use_yn boolean DEFAULT true NOT NULL
);


--
-- Name: TABLE common_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.common_code IS '공통 코드 (F9) — AI_MODEL 그룹은 요청 가능한 모델 화이트리스트로 쓰인다 (F9-04)';


--
-- Name: COLUMN common_code.group_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.common_code.group_code IS '소속 그룹 코드 (common_code_group.group_code)';


--
-- Name: COLUMN common_code.code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.common_code.code IS '코드 값 (그룹 내 고유) — AI_MODEL 그룹에서는 모델명';


--
-- Name: COLUMN common_code.code_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.common_code.code_name IS '코드 표시명';


--
-- Name: COLUMN common_code.sort_order; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.common_code.sort_order IS '화면 정렬 순서';


--
-- Name: COLUMN common_code.use_yn; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.common_code.use_yn IS '사용 여부 — false 면 선택 불가';


--
-- Name: common_code_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.common_code_group (
    group_code character varying(30) NOT NULL,
    group_name character varying(100) NOT NULL,
    description character varying(255),
    use_yn boolean DEFAULT true NOT NULL
);


--
-- Name: TABLE common_code_group; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.common_code_group IS '공통 코드 그룹 (F9) — 코드 집합의 상위 분류';


--
-- Name: COLUMN common_code_group.group_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.common_code_group.group_code IS '그룹 코드 (PK) — 예: AI_MODEL';


--
-- Name: COLUMN common_code_group.group_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.common_code_group.group_name IS '그룹 표시명';


--
-- Name: COLUMN common_code_group.description; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.common_code_group.description IS '그룹 설명';


--
-- Name: COLUMN common_code_group.use_yn; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.common_code_group.use_yn IS '사용 여부 — false 면 조회 대상에서 제외';


--
-- Name: guide; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guide (
    guide_seq bigint NOT NULL,
    user_seq bigint NOT NULL,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    is_public boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: TABLE guide; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.guide IS '사내 가이드 문서 (F4) — RAG 검색의 근거 자료. 본문이 청크로 분할돼 vector_store 에 임베딩된다';


--
-- Name: COLUMN guide.guide_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.guide.guide_seq IS '가이드 문서 식별자 (PK)';


--
-- Name: COLUMN guide.user_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.guide.user_seq IS '작성자 식별자 (app_user.user_seq)';


--
-- Name: COLUMN guide.title; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.guide.title IS '문서 제목 — 청크 메타데이터로도 복사된다(임베딩 벡터에는 미반영)';


--
-- Name: COLUMN guide.content; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.guide.content IS '문서 본문 (마크다운) — 이 값이 바뀔 때만 재임베딩한다';


--
-- Name: COLUMN guide.is_public; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.guide.is_public IS '공개 여부 — true 면 전체 공개, false 면 작성자만. RAG 접근 필터에 쓰인다 (F4-08)';


--
-- Name: COLUMN guide.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.guide.created_at IS '생성 일시';


--
-- Name: COLUMN guide.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.guide.updated_at IS '최종 수정 일시';


--
-- Name: guide_guide_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guide ALTER COLUMN guide_seq ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guide_guide_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: llm_usage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.llm_usage (
    usage_seq bigint NOT NULL,
    user_seq bigint NOT NULL,
    feature character varying(20) NOT NULL,
    model_name character varying(50),
    input_tokens integer,
    output_tokens integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: TABLE llm_usage; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.llm_usage IS 'LLM 사용량 기록 (F-OBS) — 사용자별 토큰 사용량. append-only, 과금·쿼터·남용 조사 근거';


--
-- Name: COLUMN llm_usage.usage_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.llm_usage.usage_seq IS '사용량 기록 식별자 (PK)';


--
-- Name: COLUMN llm_usage.user_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.llm_usage.user_seq IS '사용한 사용자 식별자 (app_user.user_seq)';


--
-- Name: COLUMN llm_usage.feature; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.llm_usage.feature IS '호출 기능 — CHAT(채팅)·OCR(영수증)·STT(음성전사)·SUMMARY(회의록요약)·EMBEDDING(가이드임베딩)';


--
-- Name: COLUMN llm_usage.model_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.llm_usage.model_name IS '실제 호출된 모델명 — 별칭(gemini-flash-latest)이 아니라 응답이 알려준 실모델';


--
-- Name: COLUMN llm_usage.input_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.llm_usage.input_tokens IS '입력(프롬프트) 토큰 수 — 제공자가 usage 를 주지 않는 경로(임베딩)에서는 NULL';


--
-- Name: COLUMN llm_usage.output_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.llm_usage.output_tokens IS '출력(생성) 토큰 수 — 제공자가 usage 를 주지 않는 경로(임베딩)에서는 NULL';


--
-- Name: COLUMN llm_usage.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.llm_usage.created_at IS '기록 일시';


--
-- Name: llm_usage_usage_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.llm_usage ALTER COLUMN usage_seq ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.llm_usage_usage_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receipt; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.receipt (
    receipt_seq bigint NOT NULL,
    user_seq bigint NOT NULL,
    image_path character varying(512) NOT NULL,
    pay_amount integer NOT NULL,
    biz_no character varying(10) NOT NULL,
    pay_date character varying(8) NOT NULL,
    card_name character varying(100),
    biz_no_valid boolean NOT NULL,
    select_type character varying(10) NOT NULL,
    raw_json jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: TABLE receipt; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.receipt IS '영수증 인식 결과 (F3) — 이미지를 멀티모달로 분석해 추출한 결제 내역';


--
-- Name: COLUMN receipt.receipt_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt.receipt_seq IS '영수증 식별자 (PK)';


--
-- Name: COLUMN receipt.user_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt.user_seq IS '소유자 식별자 (app_user.user_seq)';


--
-- Name: COLUMN receipt.image_path; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt.image_path IS '이미지 저장 경로 — 저장 루트는 설정값(app.upload.receipt-dir) 기준 상대경로';


--
-- Name: COLUMN receipt.pay_amount; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt.pay_amount IS '결제 금액 (원)';


--
-- Name: COLUMN receipt.biz_no; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt.biz_no IS '사업자등록번호 — 하이픈 없는 10자리';


--
-- Name: COLUMN receipt.pay_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt.pay_date IS '결제일 — YYYYMMDD 8자리 문자열';


--
-- Name: COLUMN receipt.card_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt.card_name IS '카드사명';


--
-- Name: COLUMN receipt.biz_no_valid; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt.biz_no_valid IS '사업자등록번호 체크섬 검증 통과 여부';


--
-- Name: COLUMN receipt.select_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt.select_type IS '입력 방식 — AUTO(AI 추출) | MANUAL(사용자 수기 입력)';


--
-- Name: COLUMN receipt.raw_json; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt.raw_json IS 'AI 원본 추출 결과 JSON — 재분석·디버깅용';


--
-- Name: COLUMN receipt.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt.created_at IS '저장 일시';


--
-- Name: receipt_receipt_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.receipt ALTER COLUMN receipt_seq ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.receipt_receipt_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_social_account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_social_account (
    social_seq bigint NOT NULL,
    user_seq bigint NOT NULL,
    provider character varying(20) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: TABLE user_social_account; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.user_social_account IS '소셜 로그인 연동 정보 (F1-1) — 한 계정에 여러 제공자를 연결할 수 있다';


--
-- Name: COLUMN user_social_account.social_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_social_account.social_seq IS '연동 식별자 (PK)';


--
-- Name: COLUMN user_social_account.user_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_social_account.user_seq IS '연결된 사용자 식별자 (app_user.user_seq)';


--
-- Name: COLUMN user_social_account.provider; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_social_account.provider IS '제공자 — naver | kakao | google';


--
-- Name: COLUMN user_social_account.provider_user_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_social_account.provider_user_id IS '제공자가 발급한 고유 사용자 ID — 제공자+ID 조합으로 계정을 찾는다';


--
-- Name: COLUMN user_social_account.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_social_account.created_at IS '연동 일시';


--
-- Name: user_social_account_social_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_social_account ALTER COLUMN social_seq ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_social_account_social_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vector_store; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vector_store (
    id uuid NOT NULL,
    content text,
    metadata jsonb,
    embedding public.vector(768)
);


--
-- Name: TABLE vector_store; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.vector_store IS 'Spring AI PgVectorStore 표준 스키마 — 가이드 청크 임베딩 (initialize-schema:false 라 직접 관리)';


--
-- Name: COLUMN vector_store.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.vector_store.id IS '청크 식별자 (PK, UUID)';


--
-- Name: COLUMN vector_store.content; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.vector_store.content IS '청크 본문 — 임베딩 벡터의 원천 텍스트';


--
-- Name: COLUMN vector_store.metadata; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.vector_store.metadata IS '청크 메타데이터 JSONB — {guideSeq, userSeq, title, isPublic}. 접근 필터(F4-08)와 본문 무변경 수정의 메타데이터 갱신에 쓰인다';


--
-- Name: COLUMN vector_store.embedding; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.vector_store.embedding IS '임베딩 벡터 768차원 — 모델 출력 차원과 반드시 일치해야 한다';


--
-- Name: voice_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voice_record (
    record_seq bigint NOT NULL,
    user_seq bigint NOT NULL,
    title character varying(200) NOT NULL,
    stt_text text NOT NULL,
    summary_md text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    audio_file_name character varying(200),
    origin_file_name character varying(255),
    file_size bigint,
    content_type character varying(100)
);


--
-- Name: TABLE voice_record; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.voice_record IS '음성 회의록 (F8-1) — 오디오 전사문과 AI 요약, 원본 오디오 메타데이터';


--
-- Name: COLUMN voice_record.record_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.voice_record.record_seq IS '회의록 식별자 (PK)';


--
-- Name: COLUMN voice_record.user_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.voice_record.user_seq IS '소유자 식별자 (app_user.user_seq)';


--
-- Name: COLUMN voice_record.title; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.voice_record.title IS '회의록 제목 — 미입력 시 자동 생성';


--
-- Name: COLUMN voice_record.stt_text; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.voice_record.stt_text IS '음성 전사 원문 (STT 결과)';


--
-- Name: COLUMN voice_record.summary_md; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.voice_record.summary_md IS 'AI 구조화 요약 (마크다운) — 핵심 요약/결정 사항/Action Items 3단';


--
-- Name: COLUMN voice_record.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.voice_record.created_at IS '생성 일시';


--
-- Name: COLUMN voice_record.audio_file_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.voice_record.audio_file_name IS '저장된 오디오 파일명 — 저장 루트는 설정값(app.upload.voice-dir)';


--
-- Name: COLUMN voice_record.origin_file_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.voice_record.origin_file_name IS '업로드 당시 원본 파일명 (표시용)';


--
-- Name: COLUMN voice_record.file_size; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.voice_record.file_size IS '오디오 파일 크기 (바이트)';


--
-- Name: COLUMN voice_record.content_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.voice_record.content_type IS '오디오 MIME 타입 — 재생 시 Content-Type 으로 사용';


--
-- Name: voice_record_record_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.voice_record_record_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: voice_record_record_seq_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.voice_record_record_seq_seq OWNED BY public.voice_record.record_seq;


--
-- Name: voice_record record_seq; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_record ALTER COLUMN record_seq SET DEFAULT nextval('public.voice_record_record_seq_seq'::regclass);


--
-- Name: admin_audit_log admin_audit_log_audit_seq_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_audit_log
    ADD CONSTRAINT admin_audit_log_audit_seq_pk PRIMARY KEY (audit_seq);


--
-- Name: app_user app_user_email_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_email_uk UNIQUE (email);


--
-- Name: app_user app_user_user_seq_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_user_seq_pk PRIMARY KEY (user_seq);


--
-- Name: chat_message chat_message_message_seq_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_message_seq_pk PRIMARY KEY (message_seq);


--
-- Name: chat_room chat_room_room_seq_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_room
    ADD CONSTRAINT chat_room_room_seq_pk PRIMARY KEY (room_seq);


--
-- Name: common_code_group common_code_group_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.common_code_group
    ADD CONSTRAINT common_code_group_pk PRIMARY KEY (group_code);


--
-- Name: common_code common_code_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.common_code
    ADD CONSTRAINT common_code_pk PRIMARY KEY (group_code, code);


--
-- Name: guide guide_guide_seq_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guide
    ADD CONSTRAINT guide_guide_seq_pk PRIMARY KEY (guide_seq);


--
-- Name: llm_usage llm_usage_usage_seq_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.llm_usage
    ADD CONSTRAINT llm_usage_usage_seq_pk PRIMARY KEY (usage_seq);


--
-- Name: receipt receipt_receipt_seq_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receipt
    ADD CONSTRAINT receipt_receipt_seq_pk PRIMARY KEY (receipt_seq);


--
-- Name: user_social_account user_social_account_provider_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_social_account
    ADD CONSTRAINT user_social_account_provider_uk UNIQUE (provider, provider_user_id);


--
-- Name: user_social_account user_social_account_social_seq_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_social_account
    ADD CONSTRAINT user_social_account_social_seq_pk PRIMARY KEY (social_seq);


--
-- Name: vector_store vector_store_id_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vector_store
    ADD CONSTRAINT vector_store_id_pk PRIMARY KEY (id);


--
-- Name: voice_record voice_record_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_record
    ADD CONSTRAINT voice_record_pk PRIMARY KEY (record_seq);


--
-- Name: idx_chat_message_room; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_message_room ON public.chat_message USING btree (room_seq, created_at);


--
-- Name: idx_chat_room_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_room_user ON public.chat_room USING btree (user_seq, created_at DESC);


--
-- Name: idx_llm_usage_feature_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_llm_usage_feature_created ON public.llm_usage USING btree (feature, created_at);


--
-- Name: idx_llm_usage_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_llm_usage_user_created ON public.llm_usage USING btree (user_seq, created_at);


--
-- Name: idx_receipt_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_receipt_user_created ON public.receipt USING btree (user_seq, created_at DESC);


--
-- Name: idx_user_social_account_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_social_account_user ON public.user_social_account USING btree (user_seq);


--
-- Name: idx_vector_store_embedding; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vector_store_embedding ON public.vector_store USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: idx_voice_record_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voice_record_user ON public.voice_record USING btree (user_seq, created_at DESC);


--
-- Name: common_code common_code_group_code_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.common_code
    ADD CONSTRAINT common_code_group_code_fk FOREIGN KEY (group_code) REFERENCES public.common_code_group(group_code);


--
-- Name: user_social_account user_social_account_user_seq_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_social_account
    ADD CONSTRAINT user_social_account_user_seq_fk FOREIGN KEY (user_seq) REFERENCES public.app_user(user_seq);


--
-- Name: voice_record voice_record_user_seq_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_record
    ADD CONSTRAINT voice_record_user_seq_fk FOREIGN KEY (user_seq) REFERENCES public.app_user(user_seq);


--
-- PostgreSQL database dump complete
--


